### ISSUE TITLE
--> 637             raise KeyError(key)     638         elif matches == 1:     639             return mask.argmax()  KeyError: 1

### ISSUE THREAD

**Issue by yanqiangmiffy** [Hasan-Basri-Akcay/featdist#1]
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_1920/57287498.py in <module>
----> 1 df_stats = numerical_ttt_dist(train=X_train, test=X_test, features=num_features, target='target_reg')
      2 df_stats

F:\ProgramData\Anaconda3\lib\site-packages\featdist\base.py in numerical_ttt_dist(train, test, val, features, agg_func, target, nbins, ncols, s, figsize, ylim, sharey, corr)
    126         row_dict = {}
    127         row_dict['feature'] = feature
--> 128         row_dict['train_trend_changes'] = _find_trend_changes(bins_target['bin_count'])
    129         row_dict['train_target_trend_changes'] = _find_trend_changes(bins_target[target])
    130 

F:\ProgramData\Anaconda3\lib\site-packages\featdist\base.py in _find_trend_changes(data)
    357     counts = 0
    358     for index in range(1,len(data_diff)-1):
--> 359         if data_diff[index] != data_diff[index+1]:
    360             counts+=1
    361     return counts

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    956 
    957         elif key_is_scalar:
--> 958             return self._get_value(key)
    959 
    960         if is_hashable(key):

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py in _get_value(self, label, takeable)
   1067 
   1068         # Similar to Index.get_value, but we do not fall back to positional
-> 1069         loc = self.index.get_loc(label)
   1070         return self.index._get_values_for_loc(self, loc, label)
   1071 

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3625                     "backfill or nearest lookups"
   3626                 )
-> 3627             casted_key = self._maybe_cast_indexer(key)
   3628             try:
   3629                 return self._engine.get_loc(casted_key)

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\category.py in _maybe_cast_indexer(self, key)
    469         #  because this will correctly get partial-indexing on Interval categories
    470         try:
--> 471             return self._data._unbox_scalar(key)
    472         except KeyError:
    473             if is_valid_na_for_dtype(key, self.categories.dtype):

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py in _unbox_scalar(self, key)
   1954         # searchsorted is very performance sensitive. By converting codes
   1955         # to same dtype as self.codes, we get much faster performance.
-> 1956         code = self.categories.get_loc(key)
   1957         code = self._ndarray.dtype.type(code)
   1958         return code

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\interval.py in get_loc(self, key, method, tolerance)
    635         matches = mask.sum()
    636         if matches == 0:
--> 637             raise KeyError(key)
    638         elif matches == 1:
    639             return mask.argmax()

KeyError: 1`

**Comment by Hasan-Basri-Akcay** [comment]
The Pandas version should be greater than 1.3.5

**Comment by yanqiangmiffy** [comment]
Thanks for your reply

**Comment by yanqiangmiffy** [comment]
My pandas version is 1.4.0,it has the same error，could you show your requirements.txt

**Comment by Hasan-Basri-Akcay** [comment]
pandas==1.3.5
numpy==1.19.5
matplotlib==3.5.1
scipy==1.9.0

Did you install using "pip install featdist"?

**Comment by yanqiangmiffy** [comment]
> 

yes，i use   "pip install featdist"

**Comment by yanqiangmiffy** [comment]
it works，thanks
